2024-07-07 15:17:36,506 INFO    MainThread:60780 [wandb_setup.py:_flush():76] Current SDK version is 0.17.4
2024-07-07 15:17:36,506 INFO    MainThread:60780 [wandb_setup.py:_flush():76] Configure stats pid to 60780
2024-07-07 15:17:36,506 INFO    MainThread:60780 [wandb_setup.py:_flush():76] Loading settings from C:\Users\a0975\.config\wandb\settings
2024-07-07 15:17:36,506 INFO    MainThread:60780 [wandb_setup.py:_flush():76] Loading settings from C:\Users\a0975\fl\wandb\settings
2024-07-07 15:17:36,506 INFO    MainThread:60780 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-07 15:17:36,506 INFO    MainThread:60780 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-07 15:17:36,507 INFO    MainThread:60780 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'serverwan.py', 'program_abspath': 'C:\\Users\\a0975\\fl\\serverwan.py', 'program': 'serverwan.py'}
2024-07-07 15:17:36,507 INFO    MainThread:60780 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-07 15:17:36,507 INFO    MainThread:60780 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-07-07 15:17:36,507 INFO    MainThread:60780 [wandb_init.py:_log_setup():529] Logging user logs to C:\Users\a0975\fl\wandb\run-20240707_151736-i0svsgiw\logs\debug.log
2024-07-07 15:17:36,507 INFO    MainThread:60780 [wandb_init.py:_log_setup():530] Logging internal logs to C:\Users\a0975\fl\wandb\run-20240707_151736-i0svsgiw\logs\debug-internal.log
2024-07-07 15:17:36,507 INFO    MainThread:60780 [wandb_init.py:init():569] calling init triggers
2024-07-07 15:17:36,507 INFO    MainThread:60780 [wandb_init.py:init():577] wandb.init called with sweep_config: {}
config: {}
2024-07-07 15:17:36,507 INFO    MainThread:60780 [wandb_init.py:init():619] starting backend
2024-07-07 15:17:36,507 INFO    MainThread:60780 [wandb_init.py:init():623] setting up manager
2024-07-07 15:17:36,517 INFO    MainThread:60780 [backend.py:_multiprocessing_setup():107] multiprocessing start_methods=spawn, using: spawn
2024-07-07 15:17:36,519 INFO    MainThread:60780 [wandb_init.py:init():631] backend started and connected
2024-07-07 15:17:36,530 INFO    MainThread:60780 [wandb_init.py:init():720] updated telemetry
2024-07-07 15:17:36,531 INFO    MainThread:60780 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-07 15:17:36,922 ERROR   MainThread:60780 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-07 15:17:36,923 ERROR   MainThread:60780 [wandb_init.py:init():1191] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\a0975\anaconda3\envs\fltest\lib\site-packages\wandb\sdk\wandb_init.py", line 1181, in init
    return wi.init()
  File "C:\Users\a0975\anaconda3\envs\fltest\lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-07 15:17:38,020 WARNING MsgRouterThr:60780 [router.py:message_loop():77] message_loop has been closed
